const ADD = 'ADD'
const DELETE = 'DELETE'
const UPDATE = 'UPDATE'
const SELECTED = 'SELECTED'
const DELETE_SELECTED = 'DELETE_SELECTED'
const DONE_SELECTED = 'DONE_SELECTED'
// const

export {ADD, UPDATE, DELETE, SELECTED, DELETE_SELECTED, DONE_SELECTED}